# Generated by Django 5.0.6 on 2025-01-12 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='requirements',
            field=models.TextField(default='No requirements provided'),
        ),
    ]
