version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"  # Webpack 개발 서버는 기본적으로 3000 포트 사용
    volumes:
      - ./frontend:/app
    environment:
      - CHOKIDAR_USEPOLLING=true  # 파일 변경 감지를 위해 추가
    restart: always